### ISSUE TITLE
Problem with installing openid module in OJS

### ISSUE THREAD

**Issue by orcalator** [leibniz-psychology/openid#37]
Hi,

I just installed openid plugin ver. 3.2.1 in OJS ver. 3.2.1.4 and i also installed the same plugin ver. 3.3.0.7 in OJS 3.4.0.5, but in both cases when i click “Settings” under the plugin name i get an error saying “Failed Ajax request or invalid JSON returned.”. In the error log i get:

[php7:notice] PHP Notice:  Trying to access array offset on value of type null in /var/www-data/ojs-3.2.1-4-test/plugins/generic/openid/forms/OpenIDPluginSettingsForm.inc.php on line 67, referer: https://xxx/ojs-test/index.php/index/admin/settings

[php7:error] PHP Fatal error:  Uncaught Error: Call to a member function getPath() on null in /var/www-data/ojs-3.2.1-4-test/plugins/generic/openid/forms/OpenIDPluginSettingsForm.inc.php:126
Stack trace:
#0 /var/www-data/ojs-3.2.1-4-test/plugins/generic/openid/OpenIDPlugin.inc.php(184): OpenIDPluginSettingsForm->fetch()
#1 /var/www-data/ojs-3.2.1-4-test/lib/pkp/classes/controllers/grid/plugins/PluginGridHandler.inc.php(234): OpenIDPlugin->manage()
#2 /var/www-data/ojs-3.2.1-4-test/lib/pkp/classes/core/PKPRouter.inc.php(391): PluginGridHandler->manage()
#3 /var/www-data/ojs-3.2.1-4-test/lib/pkp/classes/core/PKPComponentRouter.inc.php(257): PKPRouter->_authorizeInitializeAndCallRequest()
#4 /var/www-data/ojs-3.2.1-4-test/lib/pkp/classes/core/Dispatcher.inc.php(143): PKPComponentRouter->route()
#5 /var/www-data/ojs-3.2.1-4-test/lib/pkp/classes/core/PKPApplication.inc.php(281): Dispatcher->dispatch()
#6 /var/www-data/ojs-3.2.1-4-test/index.php(68): PKPApplication->execute()
#7 {main}
  thrown in /var/www-data/ojs-3.2.1-4-test/plugins/generic/openid/forms/OpenIDPluginSettingsForm.inc.php on line 126, referer: https://xxx/ojs-test/index.php/index/admin/settings

I also installed phpseclib that is required in composer.json

Anyone can help? Thx.

regards.

**Comment by orcalator** [comment]
After i started to debug the code, plugin magically started to work o.O
